### ISSUE TITLE
Missing upper and lower lines?

### ISSUE THREAD

**Issue by Yanis002** [Hawkrex/LiveSplit.GraphIcon#1]
I'm not sure if this is a real issue or if I just need new eyes but I can't find those little lines, I think they're cool (left is you're component and right is the original one)

![image](https://github.com/Hawkrex/LiveSplit.GraphIcon/assets/35189056/7f858431-3ac7-4161-85c2-df50b7b7c007)

**Comment by Hawkrex** [comment]
Indeed, separators are missing. Color can be changed in the settings, so I guess I did not intend to remove them.

I need to discuss it with the person who asked for the GraphIcon in the first place to see if they want an option to show/hide them.
